
services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - devlinker-network

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000" 
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - mongodb
    networks:
      - devlinker-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"  
    networks:
      - devlinker-network

volumes:
  mongodb_data:

networks:
  devlinker-network:
    driver: bridge
