apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devlinker
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/MAS00M007/DevLinker-ArgoCD
    targetRevision: master
    path: k8s
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
