apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGODB_URI: mongodb://admin:password@mongodb:27017/devlinker?authSource=admin
  JWT_SECRET: your-super-secret-jwt-key
