version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: devlinker
    volumes:
      - mongodb_data:/data/db
    networks:
      - devlinker-network

  # Backend API
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/devlinker?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - devlinker-network

  # Frontend
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devlinker-network

volumes:
  mongodb_data:

networks:
  devlinker-network:
    driver: bridge